import type { ParsedPano } from "../utils/zindDataParser";

export const MANUAL_PANOS: ParsedPano[] = [
  {
    id: "manual_floor_01_stairs",
    label: "stairs",
    imagePath: "/360Assets/panos_floor2/stairs.jpg",
    floorNumber: 1,
    panoId: "manual_stairs_01",
    cameraHeight: 1.0,
    ceilingHeight: 2.7,
    isPrimary: true,
    isInside: true,
  },
  {
    id: "manual_floor_02_upper_lobby",
    label: "upper lobby",
    imagePath: "/360Assets/panos_floor2/upperLobby.jpg",
    floorNumber: 2,
    panoId: "manual_upper_lobby_02",
    cameraHeight: 1.0,
    ceilingHeight: 2.7,
    isPrimary: true,
    isInside: true,
  },
  {
    id: "manual_floor_02_bedroom",
    label: "bedroom floor 2",
    imagePath: "/360Assets/panos_floor2/bedroom.jpg",
    floorNumber: 2,
    panoId: "manual_bedroom_02",
    cameraHeight: 1.0,
    ceilingHeight: 2.7,
    isPrimary: true,
    isInside: true,
  },
  {
    id: "manual_floor_02_bathroom",
    label: "bathroom floor 2",
    imagePath: "/360Assets/panos_floor2/bathroom.jpg",
    floorNumber: 2,
    panoId: "manual_bathroom_02",
    cameraHeight: 1.0,
    ceilingHeight: 2.7,
    isPrimary: true,
    isInside: true,
  },
  {
    id: "manual_floor_02_storage_closet",
    label: "storage closet floor 2",
    imagePath: "/360Assets/panos_floor2/closet.jpg",
    floorNumber: 2,
    panoId: "manual_storage_closet_02",
    cameraHeight: 1.5,
    ceilingHeight: 2.4,
    isPrimary: true,
    isInside: true,
  },
];
